name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: extra libraries
      run: |
        git clone --quiet https://github.com/beegee-tokyo/SX126x-Arduino.git
        mv SX126x-Arduino /home/runner/Arduino/libraries/SX126x-Arduino

    - name: test platforms
      run: python3 ci/build_platform.py nrf52840
